### ISSUE TITLE
The AI provide me the Wrong date and time.

### ISSUE THREAD

**Issue by SalmanNaghori** [babakcode/flutter_gemini#1]
The model does not provide the current time and date. I asked it for the date and time, and it provided me with today's date: **March 8, 2023**.

<img src="https://github.com/babakcode/flutter_gemini/assets/69813706/dbc73702-bf39-4c85-87c7-481e4d8a63b3" width="500" height="1000">

**Comment by pantshaswat** [comment]
Yes, if we write that prompt 'tell me time or data both', it shows irrelevant dates. However, when I tried with another similar prompt, it said, '"I do not have access to real-time information and my knowledge cutoff is April 2023, so I cannot provide the current time or date.". **I do not think it's the issue of this package as it's just forwarding the answers of Gemini.**

**Comment by Sharaddition** [comment]
@SalmanNaghori that's Gemini AI's problem, not of this package.
