### ISSUE TITLE
How to re-init apiKey while in the application

### ISSUE THREAD

**Issue by longnh2k1** [babakcode/flutter_gemini#14]
I want to re-initialize the apiKey in Gemini.init(apiKey: "--apiKye--"), what should I do without having to close the application and reopen it?

**Comment by babakcode** [comment]
It's impossible. You shouldn't use the multiple API keys for services with limited use. however, I can add this feature.

**Comment by longnh2k1** [comment]
> It's impossible. You shouldn't use the multiple API keys for services with limited use. however, I can add this feature.

I really need it, can you add that feature soon🥹?
Specifically, I want to be able to pass in any apiKey that I have received from the server, rather than assigning apiKeys in the app.

**Comment by babakcode** [comment]
Now you can use this feature on the `2.0.4-dev.1` version.

```dart
  Gemini.reInitialize(apiKey: "new api key", enableDebugging: false);
```

**Comment by longnh2k1** [comment]
> Now you can use this feature on the `2.0.4-dev.1` version.
> 
> ```dart
>   Gemini.reInitialize(apiKey: "new api key", enableDebugging: false);
> ```

Thank you very much😇💐💐
