### ISSUE TITLE
'multi-turn chat' can add image? 

### ISSUE THREAD

**Issue by wy353208214** [babakcode/flutter_gemini#18]
According to gemini [rest api](https://ai.google.dev/tutorials/rest_quickstart), we can add image to the parts. but the class 'Parts' has no attribute 'inline_data'. I know textAndImage/streamGenerateContent support it, It would be better if chat/streamChat support.

thx~

such as:
```
{
  "contents": [
    {
      "parts": [
        {
          "text": "What is this picture?"
        },
        {
          "inline_data": {
            "mime_type": "image/jpeg",
            "data": "'$(base64 -w0 image.jpg)'"
          }
        }
      ]
    }
  ]
}
```

**Comment by hortigado** [comment]
+1 I also need it

**Comment by babakcode** [comment]
Hi, I can add this feature but according to REST API documentation `Note: The gemini-pro-vision model (for text-and-image input) is not yet optimized for multi-turn conversations. Make sure to use gemini-pro and text-only input for chat use cases.` I didn't update it.

I am waiting for Google's upcoming updates.

**Comment by wy353208214** [comment]
> Hi, I can add this feature but according to REST API documentation `Note: The gemini-pro-vision model (for text-and-image input) is not yet optimized for multi-turn conversations. Make sure to use gemini-pro and text-only input for chat use cases.` I didn't update it.
> 
> I am waiting for Google's upcoming updates.

ok! thank you.
