### ISSUE TITLE
Remove the depricated gemini 1.0 vision model for image and text generation

### ISSUE THREAD

**Issue by AdvaitKale01** [babakcode/flutter_gemini#33]
Error details-
Error sending text and image: **GeminiException** => This exception was thrown because the response has a status code of 404 and RequestOptions.validateStatus was configured to throw for this status code.

The status code of 404 has the following meaning: "Client error - the request contains bad syntax or cannot be fulfilled"

Read more about status codes at https://developer.mozilla.org/en-US/docs/Web/HTTP/Status

In order to resolve this exception you typically have either to verify and fix your request code or you have to fix the server code.

Status Code: -1

**Comment by AdvaitKale01** [comment]
> @AdvaitKale01 Did you find a solution for this?

Sadly no. I am now starting to troubleshoot myself

**Comment by vincentkims49** [comment]
> > @AdvaitKale01 Did you find a solution for this?
> 
> Sadly no. I am trying to troubleshoot by my side as well. @babakcode this seems to be a critical issue with text with images section.

kindly tag me when you find one. @AdvaitKale01

**Comment by toandk** [comment]
i got the same issue, still stuck here :(

**Comment by AdvaitKale01** [comment]
So it turns out the package needs to be updated as the gemini 1.0 pro model is marked depricated by Google

![image](https://github.com/user-attachments/assets/12cfea98-ee39-4f55-990a-b93c647d0578)

And hence its API request has been removed. 

### Available models
[https://ai.google.dev/gemini-api/docs/models/gemini#gemini-1.5-flash](url)

### Solution
Simple solution is to add a parameter to include the newer model of your choice.
```
await gemini.textAndImage(
            modelName: "models/gemini-1.5-flash",
            ....
````

I am also forking the package and updating the default models.

**Comment by jasonofua** [comment]
Like @AdvaitKale01 said it is to fork the library and change  to ` modelName: "models/gemini-1.5-flash",`, i was stuck on it for long until i finally changed it

**Comment by jasonofua** [comment]
@babakcode PR for this fix https://github.com/babakcode/flutter_gemini/pull/35

**Comment by ChunhThanhDe** [comment]
Hi everyone, @jasonofua  @jasonofua 👋,

I also have the same problem with the error when using image and text generation 🖼️📝.

After debugging and finding the cause, I have the same opinion about needing to replace `"gemini-pro-vision"` with `"gemini-1.5-flash"` 🔄.

Regarding patch #35, I applied it and it works very well 👍.

I leave this comment to summarize and confirm for all other developers experiencing the same error and to provide the solution here 🔍💡.

Thanks, everyone 🙏.
