### ISSUE TITLE
Looks like there is an issue in gemini.textAndImage

### ISSUE THREAD

**Issue by leviabellar** [babakcode/flutter_gemini#36]
I'm having a problem both android and web. Maybe this is because of the new flutter version?

Error
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 296:3  throw_
packages/flutter_gemini/src/utils/gemini_exception_handler_mixin.dart 28:9   handler
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 60:31           <fn>
dart-sdk/lib/async/zone.dart 1666:54                                         runBinary
dart-sdk/lib/async/future_impl.dart 178:22                                   handleError
dart-sdk/lib/async/future_impl.dart 859:46                                   handleError

![image](https://github.com/user-attachments/assets/3268ffd1-332e-4f54-9780-8e451367a306)

**Comment by ChunhThanhDe** [comment]
I am also having an error with the case of using images with text:

**My returned exception has the following information:**

```
[log] Gemini Chat - Send Text and Image: hello  - /data/user/0/com.chunhthanhde.gemini_demo/cache/ae94c0b0-682f-45c2-ac3f-fcccd56d5dac/1000001879.jpg
[log] Gemini Chat - Error: **GeminiException** => This exception was thrown because the response has a status code of 404 and RequestOptions.validateStatus was configured to throw for this status code.
The status code of 404 has the following meaning: "Client error - the request contains bad syntax or cannot be fulfilled"
Read more about status codes at [MDN Web Docs](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status)
In order to resolve this exception you typically have either to verify and fix your request code or you have to fix the server code.

	Status Code: -1
```

**Comment by ChunhThanhDe** [comment]
Hi @leviabellar, The solution you need is in #33.

**Comment by leviabellar** [comment]
Yep. Found it and forgot to mark this as resolved. Thanks so much
