### ISSUE TITLE
Error in gemini function: **GeminiException** => This exception was thrown because the response has a status code of 503

### ISSUE THREAD

**Issue by Jamie123234** [babakcode/flutter_gemini#43]

**Comment by Jamie123234** [comment]
We need an alternative model. If one model is overloaded it should try switch to another. Your package was offline last night. Even your github example was not working. The entire gemini-flutter package was throwing gemini exception 503

**Comment by babakcode** [comment]
Hi @Jamie123234, Thank you for opening the issue. I'll update the package and add other features today. Please be patient.

**Comment by Jamie123234** [comment]
Afternoon @babakcode. I really appreciate that. Thanks a million. Will do :)

**Comment by Jamie123234** [comment]
Let me know if you need any more information from me. 
I did try checking the Gemini's API itself, but the outage seemed package specific.
The Gemini 1.5 flash model was working on Google's main API playground, but the flutter-gemini package was offline and throwing error 503. It is working fine now this morning, but with regards to stability, this may happen again. I have built an entire application depending on this package, so my app kind of breaks😂.

**Comment by babakcode** [comment]
It appears that Google deprecates older models upon the release of new ones. To address this🤷‍♂️, I will treat this feature as dynamic and implement functionality to retrieve the list of available models, ensuring that the most up-to-date model is always selected. Given the circumstances, it is unlikely that this approach will incur additional costs for certain free models. Therefore, I will design this feature to be optional, allowing users to enable it as needed.

**Comment by Jamie123234** [comment]
That sounds like a good approach. Thanks a lot. 

Just to clarify, by implementing this dynamic retrieval of the latest available models, in essence, will it automatically switch over to the latest model and not get stuck on the deprecated one? 

Also, there is one confusion I have, if you say that Google is marking some models as deprecated, then why is it working again this morning? Surely, if something is marked as deprecated, it would stay deprecated?

**Comment by babakcode** [comment]
Allow me to clarify my earlier point:

The application retrieves available models each time it is launched and selects models relevant to specific methods. For instance, it chooses the latest model for standard text generation tasks. The issue with deprecated models is that they do not consistently function as expected.

**Comment by Jamie123234** [comment]
I understand. Thank you for explaining. 

It might be worth mentioning that the Gemini exception of 503 was thrown when I called the textAndImage method.

I am only telling you this in case it is helpful, I understand Google is deprecating the models as you have mentioned above. I agree that this dynamic retrieval you are trying to implement should be a valid solution.

**Comment by Jamie123234** [comment]
Hi @babakcode, I see you have updated the package. Thanks again. 
However, under the available part types on the package's homepage, you mention that the Part.file will be updated. 
What do you mean by this, as when I try add another part of type Part.file after a Part.text I get Gemini Exception error 400.
Have you not added the ability to add images with a prompt yet? 
Am I doing this incorrectly?
Here is my code below:
```
Gemini.init(apiKey: apiKey);
  final gemini = Gemini.instance;
  final file = File(image);

  try {
    print("Starting Gemini API call...");
    final response = await gemini.prompt(
      parts: [
        Part.text("Scan this document"),
        Part.file(FileDataPart(fileUri: file.uri.path))
      ],
    ).then((value) => value?.output);
```
